# Generated by Django 3.2 on 2024-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recur_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('NONE', 'None')], default='NONE', max_length=10),
        ),
    ]
